version: '3'
services:
  webclient:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
    links:
      - webapi

  webapi:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "5000:5000"
