version: '3'
services:
  webclient:
    image: node:22
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
    links:
      - webapi

  webapi:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/appdb
      - JWT_SECRET_KEY=super-secret-key

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
