name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: WebClient/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./WebClient

      - name: Run Vitest
        run: npm test
        working-directory: ./WebClient