name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: via-sep4-frontend
  IMAGE_NAME: ghcr.io/dk-sep4-s25-viauc/frontend-service/my-app

on:
  push:
    branches: [ main, dev]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
