name: Build and Push Docker Image After PR Merge

on:
  pull_request:
    branches: [ main, dev, feature/main ]
    types: [ closed ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./WebClient
          file: ./WebClient/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/frontend-service/my-app:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/frontend-service/my-app:${{ github.sha }}
