name: Build and Cache Docker Image

on:
  push:
    branches: [ feature/main ]
  pull_request:
    branches: [ feature/main ]
    
permissions:
  contents: read
  packages: write

jobs:
  docker-build-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            docker-cache-${{ github.ref }}-
            docker-cache-

      - name: Build and push Docker image (cached)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/frontend-service/my-app:cached
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
